backend:
  name: git-gateway
  repo: canada-ca/canada-ca-jekyll-boilerplate

# This line should *not* be indented
publish_mode: "editorial_workflow"
media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - create: true
    filter: {field: "language", value: "en"}
    fields:
      - {label: "Language", name: "language", widget: "select", options: ["en", "fr"]}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Content", name: "body", widget: "markdown"}
      - {label: "French equivalent", name: "altLangFile", widget: "string"}
    folder: "_pages/en"
    identifier_field: title
    label: "Pages in English"
    name: "pages-en"
  - create: true
    filter: {field: "language", value: "fr"}
    fields:
      - {label: "Langue", name: "language", widget: "select", options: ["en", "fr"]}
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Contenu", name: "body", widget: "markdown"}
      - {label: "Équivalent en anglais", name: "altLangFile", widget: "string"}
    folder: "_pages/fr"
    identifier_field: title
    label: "Pages en français"
    name: "pages-fr"